# Data Pooling: Organic Dyes 

This shows the process of taking data from disprate resources and placing them into a single file. This will result in the dataset that we will be using for curation.

This entire process can also be done by running "DyePooling.py"

In [1]:

import pandas as pd
import os


PATH = os.getcwd()
data_path = PATH +"/Dye_lake/"

In [2]:
# load the data from Deep4Chem

dfc = pd.read_csv(data_path+'deep4chem.csv')
dfc

,Tag,SMILES,Solvent,Absorption max (nm),Emission max (nm),Lifetime (ns),Quantum yield,log(e/mol-1 dm3 cm-1),abs FWHM (cm-1),emi FWHM (cm-1),abs FWHM (nm),emi FWHM (nm),Molecular weight (g mol-1),Reference
0,1,N#Cc1cc2ccc(O)cc2oc1=O,O,355.0,410.00,2.804262,NaN,NaN,NaN,NaN,NaN,NaN,187.15370,DOI: 10.1021/acs.jpcb.5b09905
1,2,N#Cc1cc2ccc([O-])cc2oc1=O,O,408.0,450.00,3.961965,NaN,NaN,NaN,NaN,NaN,43.0,186.14576,DOI: 10.1021/acs.jpcb.5b09905
2,3,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,ClC(Cl)Cl,526.0,535.00,3.602954,NaN,NaN,NaN,NaN,NaN,NaN,1061.54348,https://doi.org/10.1002/smll.201901342
3,4,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CC#N,514.0,553.72,3.810000,NaN,NaN,NaN,NaN,NaN,67.4,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
4,5,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CS(C)=O,524.0,555.00,4.700000,NaN,NaN,NaN,NaN,58.0,50.0,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20231,20232,N#Cc1c(N2CCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.41992,DOI: 10.1021/ol9000679
20232,20233,N#Cc1c(N2CCCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.44680,DOI: 10.1021/ol9000679
20233,20234,N#Cc1c(N2CCCCC2)cc(-c2cccc3ccccc23)c2c1C(=O)c1...,C1CCOC1,344.0,460.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20234,20235,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccccc3c2)c2c1C(=O)c1...,C1CCOC1,346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20235,20236,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,C1CCOC1,344.0,473.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,488.58856,DOI: 10.1021/ol9000679

These properties are dependent on a sovent, so lets mark them as such

In [3]:
#rename solvent dependet properties

exclude = ['SMILES','Tag']

dfc.rename(columns=lambda x: x + ('SolventDependent') if x not in exclude else x, inplace=True)
dfc

,Tag,SMILES,SolventSolventDependent,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,emi FWHM (nm)SolventDependent,Molecular weight (g mol-1)SolventDependent,ReferenceSolventDependent
0,1,N#Cc1cc2ccc(O)cc2oc1=O,O,355.0,410.00,2.804262,NaN,NaN,NaN,NaN,NaN,NaN,187.15370,DOI: 10.1021/acs.jpcb.5b09905
1,2,N#Cc1cc2ccc([O-])cc2oc1=O,O,408.0,450.00,3.961965,NaN,NaN,NaN,NaN,NaN,43.0,186.14576,DOI: 10.1021/acs.jpcb.5b09905
2,3,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,ClC(Cl)Cl,526.0,535.00,3.602954,NaN,NaN,NaN,NaN,NaN,NaN,1061.54348,https://doi.org/10.1002/smll.201901342
3,4,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CC#N,514.0,553.72,3.810000,NaN,NaN,NaN,NaN,NaN,67.4,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
4,5,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CS(C)=O,524.0,555.00,4.700000,NaN,NaN,NaN,NaN,58.0,50.0,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20231,20232,N#Cc1c(N2CCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.41992,DOI: 10.1021/ol9000679
20232,20233,N#Cc1c(N2CCCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.44680,DOI: 10.1021/ol9000679
20233,20234,N#Cc1c(N2CCCCC2)cc(-c2cccc3ccccc23)c2c1C(=O)c1...,C1CCOC1,344.0,460.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20234,20235,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccccc3c2)c2c1C(=O)c1...,C1CCOC1,346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20235,20236,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,C1CCOC1,344.0,473.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,488.58856,DOI: 10.1021/ol9000679

In [4]:
# the tag is not needed 
dfc = dfc.drop(['Tag'], axis =1)

In [5]:
dfc

,SMILES,SolventSolventDependent,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,emi FWHM (nm)SolventDependent,Molecular weight (g mol-1)SolventDependent,ReferenceSolventDependent
0,N#Cc1cc2ccc(O)cc2oc1=O,O,355.0,410.00,2.804262,NaN,NaN,NaN,NaN,NaN,NaN,187.15370,DOI: 10.1021/acs.jpcb.5b09905
1,N#Cc1cc2ccc([O-])cc2oc1=O,O,408.0,450.00,3.961965,NaN,NaN,NaN,NaN,NaN,43.0,186.14576,DOI: 10.1021/acs.jpcb.5b09905
2,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,ClC(Cl)Cl,526.0,535.00,3.602954,NaN,NaN,NaN,NaN,NaN,NaN,1061.54348,https://doi.org/10.1002/smll.201901342
3,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CC#N,514.0,553.72,3.810000,NaN,NaN,NaN,NaN,NaN,67.4,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
4,[O-]c1c(-c2nc3ccccc3s2)cc2ccc3cccc4ccc1c2c34,CS(C)=O,524.0,555.00,4.700000,NaN,NaN,NaN,NaN,58.0,50.0,350.42028,https://doi.org/10.1016/j.snb.2018.10.043
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20231,N#Cc1c(N2CCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.41992,DOI: 10.1021/ol9000679
20232,N#Cc1c(N2CCCCC2)cc(-c2ccccc2)c2c1C(=O)c1ccccc1-2,C1CCOC1,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.44680,DOI: 10.1021/ol9000679
20233,N#Cc1c(N2CCCCC2)cc(-c2cccc3ccccc23)c2c1C(=O)c1...,C1CCOC1,344.0,460.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20234,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccccc3c2)c2c1C(=O)c1...,C1CCOC1,346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.50668,DOI: 10.1021/ol9000679
20235,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,C1CCOC1,344.0,473.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,488.58856,DOI: 10.1021/ol9000679

Now we load the Ocelot database

In [6]:
oclt = pd.read_csv(data_path+"ocelot_data.csv")
oclt

,identifier,vie,aie,vea,aea,hl,s0s1,s0t1,hr,cr2,cr1,er,ar1,ar2,lumo,homo,smiles
0,com_k08070s,6.358147,6.315118,-1.948396,-2.007735,3.720343,1.7040,0.5236,0.085257,0.042227,0.043029,0.119082,0.059339,0.059743,-2.292833,-6.013175,C#Cc1c2cc3ccc(F)cc3cc2c(C#C)c2cc3ccc(F)cc3cc12
1,com_k15193,6.074694,5.959557,-0.849659,-0.940131,5.243637,2.3318,1.2356,0.240012,0.124876,0.115136,0.180154,0.090472,0.089682,-0.832125,-6.075761,C#Cc1c2cc3ccccn3c2c(C#C)c2cc3ccccn3c12
2,com_mo_mhr124_0m,6.471826,6.340867,-2.128486,-2.228622,3.665103,1.0567,0.4282,0.249591,0.118631,0.130960,0.184307,0.100136,0.084171,-2.421815,-6.086918,Fc1cc2c(s1)-c1cc3c(cc1=C2c1ccccc1)-c1sc(F)cc1C...
3,com_x12014nx,6.278478,6.233241,-1.875712,-1.938982,4.459404,1.9350,0.4019,0.088969,0.043732,0.045237,0.124782,0.063270,0.061512,-1.835409,-6.294813,C#Cc1c2cc3cc4cc(I)sc4cc3cc2c(C#C)c2cc3sccc3cc12
4,csd_ATUWIW,6.905373,6.740939,0.007461,-0.190248,6.473048,3.7065,2.6162,0.321247,0.156813,0.164434,0.410310,0.197709,0.212601,-0.205990,-6.679038,Clc1cc(-c2nc(-c3ccco3)[nH]c2-c2csc(Cl)c2)cs1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25246,csd_ZZZJHW01,7.842970,7.634046,0.334581,0.016591,8.174305,4.7486,3.2492,0.422431,0.213507,0.208925,0.648678,0.317990,0.330688,0.334972,-7.839332,c1ccc(-c2cccc(-c3ccccc3-c3ccccc3)c2)cc1
25247,csd_ZZZKHY01,7.648538,7.418476,0.209216,-0.161869,7.859741,4.6455,3.1716,0.441622,0.211559,0.230062,0.675737,0.371086,0.304651,0.210072,-7.649669,c1ccc(-c2ccc(-c3ccccc3-c3ccccc3)cc2)cc1
25248,csd_ZZZNNM01,7.633354,7.503261,0.566471,0.421140,8.231449,4.4874,2.6119,0.260844,0.130751,0.130093,0.286602,0.145331,0.141271,0.595658,-7.635791,c1cc2c3c(cccc3c1)C1CCC21
25249,csd_ZZZQPA01,8.009415,7.619978,0.141381,-0.239090,7.721779,4.6109,3.5264,0.748392,0.358955,0.389437,0.749682,0.380471,0.369211,-0.130887,-7.852666,O=C(Oc1ccc2c(c1)CCC1C2CCC2CCCC21)c1ccccc1
25250,csd_ZZZTCK01,8.074267,7.885859,-0.108682,-0.402472,8.098657,4.5364,3.0671,0.372596,0.184189,0.188408,0.548135,0.293790,0.254345,-0.002993,-8.101650,Clc1ccc(-c2cc(-c3ccc(Cl)cc3)cc(-c3ccc(Cl)cc3)c...

The columns are not named very well, so we will name them with less ambiguity

In [7]:
oclt.columns = [
    'identifier', 'VerticalIonizationE', 'AdiabaticIonizationE', 'VerticalElectronAffinity', 'AdiabaticElectronAffinity', 'HLGap', 'lowest-lyingSinglet', 'lowest-lyingTriplet', 'HoleReorganizationE', 'CatIonRelax2', 'CationRelax1', 'ElectronReorganizationE', 'AnIonRelax1', 'AnionRelax2', 'lumo', 'homo', 'SMILES'
]
oclt

,identifier,VerticalIonizationE,AdiabaticIonizationE,VerticalElectronAffinity,AdiabaticElectronAffinity,HLGap,lowest-lyingSinglet,lowest-lyingTriplet,HoleReorganizationE,CatIonRelax2,CationRelax1,ElectronReorganizationE,AnIonRelax1,AnionRelax2,lumo,homo,SMILES
0,com_k08070s,6.358147,6.315118,-1.948396,-2.007735,3.720343,1.7040,0.5236,0.085257,0.042227,0.043029,0.119082,0.059339,0.059743,-2.292833,-6.013175,C#Cc1c2cc3ccc(F)cc3cc2c(C#C)c2cc3ccc(F)cc3cc12
1,com_k15193,6.074694,5.959557,-0.849659,-0.940131,5.243637,2.3318,1.2356,0.240012,0.124876,0.115136,0.180154,0.090472,0.089682,-0.832125,-6.075761,C#Cc1c2cc3ccccn3c2c(C#C)c2cc3ccccn3c12
2,com_mo_mhr124_0m,6.471826,6.340867,-2.128486,-2.228622,3.665103,1.0567,0.4282,0.249591,0.118631,0.130960,0.184307,0.100136,0.084171,-2.421815,-6.086918,Fc1cc2c(s1)-c1cc3c(cc1=C2c1ccccc1)-c1sc(F)cc1C...
3,com_x12014nx,6.278478,6.233241,-1.875712,-1.938982,4.459404,1.9350,0.4019,0.088969,0.043732,0.045237,0.124782,0.063270,0.061512,-1.835409,-6.294813,C#Cc1c2cc3cc4cc(I)sc4cc3cc2c(C#C)c2cc3sccc3cc12
4,csd_ATUWIW,6.905373,6.740939,0.007461,-0.190248,6.473048,3.7065,2.6162,0.321247,0.156813,0.164434,0.410310,0.197709,0.212601,-0.205990,-6.679038,Clc1cc(-c2nc(-c3ccco3)[nH]c2-c2csc(Cl)c2)cs1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25246,csd_ZZZJHW01,7.842970,7.634046,0.334581,0.016591,8.174305,4.7486,3.2492,0.422431,0.213507,0.208925,0.648678,0.317990,0.330688,0.334972,-7.839332,c1ccc(-c2cccc(-c3ccccc3-c3ccccc3)c2)cc1
25247,csd_ZZZKHY01,7.648538,7.418476,0.209216,-0.161869,7.859741,4.6455,3.1716,0.441622,0.211559,0.230062,0.675737,0.371086,0.304651,0.210072,-7.649669,c1ccc(-c2ccc(-c3ccccc3-c3ccccc3)cc2)cc1
25248,csd_ZZZNNM01,7.633354,7.503261,0.566471,0.421140,8.231449,4.4874,2.6119,0.260844,0.130751,0.130093,0.286602,0.145331,0.141271,0.595658,-7.635791,c1cc2c3c(cccc3c1)C1CCC21
25249,csd_ZZZQPA01,8.009415,7.619978,0.141381,-0.239090,7.721779,4.6109,3.5264,0.748392,0.358955,0.389437,0.749682,0.380471,0.369211,-0.130887,-7.852666,O=C(Oc1ccc2c(c1)CCC1C2CCC2CCCC21)c1ccccc1
25250,csd_ZZZTCK01,8.074267,7.885859,-0.108682,-0.402472,8.098657,4.5364,3.0671,0.372596,0.184189,0.188408,0.548135,0.293790,0.254345,-0.002993,-8.101650,Clc1ccc(-c2cc(-c3ccc(Cl)cc3)cc(-c3ccc(Cl)cc3)c...

Finally, lets load the web-scraped data

In [8]:
wdv = pd.read_csv(data_path+'WDVDataComplete_uncurated.csv')
wdv

,name,CAS,LF,Standard,Dyetype,class,properties,SMILES,Category,Color,...,ColorWater,WoolDyeTox,SilkDye,PolyamideDye,PolyamideFiberDye,BlendedFabricDye,PolyesterDye,LeatherDye,PolyethyleneDye,PolyvinylDye
0,"Name:C.I.Acid Red 92,C.I. 45410",18472-87-2,3,AATCC,AcidDye,Molecular Structure: Xanthene,Properties and Applications: brilliant pink. S...,[Na+].[Na+].[O-]c1c(Br)cc2c(Oc3c(Br)c([O-])c(B...,NaN,False,...,False,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
1,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...,[H]N(/N=C1\C(=O)c2cc(N)ccc2C=C1S(=O)(=O)O[Na])...,acid-dyes,{'red'},...,False,1.0,1.0,1.0,-1.0,1.0,1.0,1.0,0.0,1.0
2,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...,[H]N(/N=C1\C(=O)c2cc(N)ccc2C=C1S(=O)(=O)O[Na])...,acid-dyes,{'red'},...,False,1.0,1.0,1.0,-1.0,1.0,1.0,1.0,0.0,1.0
3,"Name:C.I.Acid Black 242,C.I.30028",152521-111-4,4,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,[H]N(/N=C1\C(=O)c2c(cc(S([Na])[Og])c(/N=N/c3cc...,acid-dyes,{'black'},...,False,1.0,1.0,1.0,1.0,0.0,-1.0,1.0,0.0,0.0
4,"Name:C.I.Acid Black 241,C.I.30024",84170-03-6,4-5,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,[H]N(/N=C1\C(=O)c2c(cc(S(=O)(=O)O[Na])c(/N=N/c...,acid-dyes,{'black'},...,{'black'},1.0,-1.0,0.0,0.0,-1.0,1.0,-1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3373,"Name:C.I.Solubilised Vat Yellow 3 ,C.I.61726",6711-83-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow.,[Na+].[Na+].[O-][S](=O)(=O)Oc1c2cccc(NC(=O)c3c...,vat-dyes,False,...,{'yellow'},-1.0,0.0,-1.0,-1.0,-1.0,0.0,1.0,1.0,0.0
3374,"Name:C.I.Vat Yellow 3,C.I.61725",82-18-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow. Yellow p...,O=C(Nc1cccc2C(=O)c3c(NC(=O)c4ccccc4)cccc3C(=O)...,vat-dyes,"{'yellow', 'yellow powder'}",...,{'yellow'},1.0,0.0,-1.0,1.0,1.0,1.0,1.0,1.0,0.0
3375,"Name:C.I.Solubilised Vat Yellow 2,C.I.67301",13109-68-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yellow.,O=S(=O)(O[Na])Oc1c2ccc3nc(-c4ccccc4)sc3c2c(OS(...,vat-dyes,{'green'},...,{'green'},0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,-1.0
3376,"Name:C.I.Vat Yellow 2,C.I.67300",129-09-9,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yello...,O=C1c2ccc3nc(sc3c2C(=O)c4ccc5nc(sc5c14)c6ccccc...,vat-dyes,False,...,"{'color green', 'green'}",0.0,-1.0,-1.0,0.0,1.0,0.0,0.0,1.0,1.0
3377,"Name:C.I.Solubilised Vat Yellow 1,C.I.70601",6487-09-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: red light yellow.,O=S(=O)(OOO[Na])OC1C/C=C\c2cc3c(ccc4c3c(n2)-c2...,vat-dyes,{'red'},...,False,-1.0,1.0,1.0,1.0,-1.0,0.0,0.0,0.0,1.0

like in  ocelot, some columns should be renamed to clear up ambiguity

In [9]:

wdv.replace({1.0: 'yes', 0.0: 'unknown', -1.0: 'no'}, inplace=True)

In [10]:
wdv

,name,CAS,LF,Standard,Dyetype,class,properties,SMILES,Category,Color,...,ColorWater,WoolDyeTox,SilkDye,PolyamideDye,PolyamideFiberDye,BlendedFabricDye,PolyesterDye,LeatherDye,PolyethyleneDye,PolyvinylDye
0,"Name:C.I.Acid Red 92,C.I. 45410",18472-87-2,3,AATCC,AcidDye,Molecular Structure: Xanthene,Properties and Applications: brilliant pink. S...,[Na+].[Na+].[O-]c1c(Br)cc2c(Oc3c(Br)c([O-])c(B...,NaN,False,...,False,unknown,yes,unknown,yes,yes,yes,unknown,unknown,yes
1,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...,[H]N(/N=C1\C(=O)c2cc(N)ccc2C=C1S(=O)(=O)O[Na])...,acid-dyes,{'red'},...,False,yes,yes,yes,no,yes,yes,yes,unknown,yes
2,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...,[H]N(/N=C1\C(=O)c2cc(N)ccc2C=C1S(=O)(=O)O[Na])...,acid-dyes,{'red'},...,False,yes,yes,yes,no,yes,yes,yes,unknown,yes
3,"Name:C.I.Acid Black 242,C.I.30028",152521-111-4,4,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,[H]N(/N=C1\C(=O)c2c(cc(S([Na])[Og])c(/N=N/c3cc...,acid-dyes,{'black'},...,False,yes,yes,yes,yes,unknown,no,yes,unknown,unknown
4,"Name:C.I.Acid Black 241,C.I.30024",84170-03-6,4-5,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,[H]N(/N=C1\C(=O)c2c(cc(S(=O)(=O)O[Na])c(/N=N/c...,acid-dyes,{'black'},...,{'black'},yes,no,unknown,unknown,no,yes,no,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3373,"Name:C.I.Solubilised Vat Yellow 3 ,C.I.61726",6711-83-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow.,[Na+].[Na+].[O-][S](=O)(=O)Oc1c2cccc(NC(=O)c3c...,vat-dyes,False,...,{'yellow'},no,unknown,no,no,no,unknown,yes,yes,unknown
3374,"Name:C.I.Vat Yellow 3,C.I.61725",82-18-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow. Yellow p...,O=C(Nc1cccc2C(=O)c3c(NC(=O)c4ccccc4)cccc3C(=O)...,vat-dyes,"{'yellow', 'yellow powder'}",...,{'yellow'},yes,unknown,no,yes,yes,yes,yes,yes,unknown
3375,"Name:C.I.Solubilised Vat Yellow 2,C.I.67301",13109-68-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yellow.,O=S(=O)(O[Na])Oc1c2ccc3nc(-c4ccccc4)sc3c2c(OS(...,vat-dyes,{'green'},...,{'green'},unknown,yes,yes,unknown,yes,unknown,yes,yes,no
3376,"Name:C.I.Vat Yellow 2,C.I.67300",129-09-9,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yello...,O=C1c2ccc3nc(sc3c2C(=O)c4ccc5nc(sc5c14)c6ccccc...,vat-dyes,False,...,"{'color green', 'green'}",unknown,no,no,unknown,yes,unknown,unknown,yes,yes
3377,"Name:C.I.Solubilised Vat Yellow 1,C.I.70601",6487-09-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: red light yellow.,O=S(=O)(OOO[Na])OC1C/C=C\c2cc3c(ccc4c3c(n2)-c2...,vat-dyes,{'red'},...,False,no,yes,yes,yes,no,unknown,unknown,unknown,yes

one last step: denote the origin of each data point before they are all merged into the same file

In [11]:
wdv['origin'] = 'Webscraping'
oclt['origin'] = 'ocelot'
dfc['origin'] = 'Deep4Chem'

In [12]:
# merge the dataframes into one and save
merged_df = dfc.merge(oclt, on=['SMILES','origin'], how='outer')

In [21]:
merged_df.columns

Index(['SMILES', 'SolventSolventDependent',
       'Absorption max (nm)SolventDependent',
       'Emission max (nm)SolventDependent', 'Lifetime (ns)SolventDependent',
       'Quantum yieldSolventDependent',
       'log(e/mol-1 dm3 cm-1)SolventDependent',
       'abs FWHM (cm-1)SolventDependent', 'emi FWHM (cm-1)SolventDependent',
       'abs FWHM (nm)SolventDependent', 'emi FWHM (nm)SolventDependent',
       'Molecular weight (g mol-1)SolventDependent',
       'ReferenceSolventDependent', 'origin', 'identifier',
       'VerticalIonizationE', 'AdiabaticIonizationE',
       'VerticalElectronAffinity', 'AdiabaticElectronAffinity', 'HLGap',
       'lowest-lyingSinglet', 'lowest-lyingTriplet', 'HoleReorganizationE',
       'CatIonRelax2', 'CationRelax1', 'ElectronReorganizationE',
       'AnIonRelax1', 'AnionRelax2', 'lumo', 'homo', 'name', 'CAS', 'LF',
       'Standard', 'Dyetype', 'class', 'properties', 'Category', 'Color',
       'SolubleAcetone', 'SolubleEthanol', 'SolubleAlcohol',
       'ColorSulfuricAcid', 'ColorHydrochloricAcid', 'ColorWater',
       'WoolDyeTox', 'SilkDye', 'PolyamideDye', 'PolyamideFiberDye',
       'BlendedFabricDye', 'PolyesterDye', 'LeatherDye', 'PolyethyleneDye',
       'PolyvinylDye'],
      dtype='object')

In [13]:
merged_df

,SMILES,SolventSolventDependent,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,...,lowest-lyingSinglet,lowest-lyingTriplet,HoleReorganizationE,CatIonRelax2,CationRelax1,ElectronReorganizationE,AnIonRelax1,AnionRelax2,lumo,homo
0,B1BN(c2ccccc2)C=CN1c1ccccc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0081,2.7386,0.352402,0.176728,0.175675,0.757505,0.391920,0.365584,-0.168983,-7.126938
1,B1Bc2ccsc2-c2sccc21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.9465,1.3705,0.559270,0.285256,0.274014,0.297334,0.196153,0.101181,-2.073781,-7.336193
2,B1Bc2sccc2-c2ccsc21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.1564,1.5090,0.645390,0.384998,0.260392,0.181965,0.090087,0.091878,-2.124394,-7.602865
3,B1C(c2ccccc2)=C(c2ccccc2)C(c2ccccc2)=C(c2ccccc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.2733,2.5982,0.409423,0.198506,0.210918,0.454791,0.219186,0.235605,-0.737429,-6.888294
4,B1C(c2ccccc2)=C(c2ccccc2)C(c2ccccc2)=C(c2ccccc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9219,2.7498,0.420885,0.200549,0.220336,0.585802,0.297287,0.288515,-0.254971,-7.028977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45482,c1scc2c1sc1cscc12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9434,2.9604,0.156415,0.078717,0.077698,0.259116,0.126740,0.132376,-0.023130,-7.003670
45483,n1n[nH]c(-c2nnn[nH]2)n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.6645,4.1304,0.908711,0.475759,0.432952,0.616781,0.309777,0.307004,-0.119730,-11.108510
45484,n1n[nH]c(Nc2nnc(Nc3nnn[nH]3)nn2)n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.3026,1.4675,0.288886,0.153472,0.135413,0.993554,0.482406,0.511148,-2.211743,-9.385212
45485,n1nc(-c2nn[nH]n2)n[nH]1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.8712,4.2457,0.764160,0.400480,0.363679,0.661419,0.327795,0.333624,0.928997,-10.443463
45486,n1onc2c1Nc1nonc1-c1nonc1-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0354,3.4909,0.291594,0.151882,0.139713,0.587978,0.293021,0.294956,-0.785593,-9.757736

In [14]:
merged_df = merged_df.merge(wdv,on=['SMILES','origin'], how='outer')

In [15]:
merged_df

,SMILES,SolventSolventDependent,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,...,ColorWater,WoolDyeTox,SilkDye,PolyamideDye,PolyamideFiberDye,BlendedFabricDye,PolyesterDye,LeatherDye,PolyethyleneDye,PolyvinylDye
0,***.**N(CC(=O)OC)C(=O)O.*1*2**12.COC(=O)CC(=O)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'green'},no,yes,yes,unknown,unknown,yes,unknown,unknown,yes
1,**.**,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'green'},no,yes,unknown,yes,no,no,yes,unknown,yes
2,**.*C.CC=C1CC2N=C3C4=C(C=CC=C4)C4=N3[Cu]35N6C(...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'blue'},unknown,unknown,no,unknown,unknown,yes,yes,unknown,no
3,**.O=C(O)CC(=O)O.[H]N(c1cccc(S(=O)(=O)O)c1)c1n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'red'},yes,unknown,no,yes,no,yes,yes,yes,yes
4,**.[H]N(C1=NC(Cl)=NC(N(CC)C2=CC(C(S(=O)(=O)O)S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'blue'},unknown,yes,yes,yes,unknown,no,yes,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'yellow'},yes,unknown,no,unknown,yes,yes,yes,unknown,no
48861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'red'},no,yes,unknown,yes,yes,no,yes,yes,yes
48862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'yellow'},unknown,unknown,yes,yes,unknown,unknown,unknown,unknown,unknown
48863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,no,yes,no,yes,yes,unknown,unknown,unknown,unknown
48864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,unknown,yes,unknown,unknown,yes,yes,unknown,unknown,unknown

In [22]:
merged_df =merged_df.dropna(subset='SMILES')
merged_df

,SMILES,SolventSolventDependent,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,...,ColorWater,WoolDyeTox,SilkDye,PolyamideDye,PolyamideFiberDye,BlendedFabricDye,PolyesterDye,LeatherDye,PolyethyleneDye,PolyvinylDye
0,***.**N(CC(=O)OC)C(=O)O.*1*2**12.COC(=O)CC(=O)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'green'},no,yes,yes,unknown,unknown,yes,unknown,unknown,yes
1,**.**,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'green'},no,yes,unknown,yes,no,no,yes,unknown,yes
2,**.*C.CC=C1CC2N=C3C4=C(C=CC=C4)C4=N3[Cu]35N6C(...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'blue'},unknown,unknown,no,unknown,unknown,yes,yes,unknown,no
3,**.O=C(O)CC(=O)O.[H]N(c1cccc(S(=O)(=O)O)c1)c1n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'red'},yes,unknown,no,yes,no,yes,yes,yes,yes
4,**.[H]N(C1=NC(Cl)=NC(N(CC)C2=CC(C(S(=O)(=O)O)S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,{'blue'},unknown,yes,yes,yes,unknown,no,yes,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47843,c1scc2c1sc1cscc12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47844,n1n[nH]c(-c2nnn[nH]2)n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47845,n1n[nH]c(Nc2nnc(Nc3nnn[nH]3)nn2)n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47846,n1nc(-c2nn[nH]n2)n[nH]1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47847,n1onc2c1Nc1nonc1-c1nonc1-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Export the summary table to make sure the data lake is ready for curation

DyeDescription = merged_df.describe()

In [24]:
DyeDescription

,Absorption max (nm)SolventDependent,Emission max (nm)SolventDependent,Lifetime (ns)SolventDependent,Quantum yieldSolventDependent,log(e/mol-1 dm3 cm-1)SolventDependent,abs FWHM (cm-1)SolventDependent,emi FWHM (cm-1)SolventDependent,abs FWHM (nm)SolventDependent,emi FWHM (nm)SolventDependent,Molecular weight (g mol-1)SolventDependent,...,lowest-lyingSinglet,lowest-lyingTriplet,HoleReorganizationE,CatIonRelax2,CationRelax1,ElectronReorganizationE,AnIonRelax1,AnionRelax2,lumo,homo
count,17295.000000,18142.000000,6960.000000,13837.000000,8041.000000,747.000000,627.000000,3592.000000,7198.000000,20236.000000,...,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000,25251.000000
mean,427.616868,500.243574,7.233011,0.345025,4.391733,2894.623427,2892.696970,66.418291,74.530689,475.133600,...,3.568533,2.462453,0.420515,0.212188,0.208327,0.484817,0.247258,0.237559,-0.622439,-7.311861
std,106.102597,94.141225,40.096921,0.307890,0.582147,1546.003964,1414.210365,24.441340,28.850144,247.202212,...,0.643355,0.548173,0.183761,0.100070,0.095519,0.175064,0.096390,0.087482,0.696491,0.671970
min,127.700000,247.000000,0.000100,0.000000,1.079181,575.000000,650.000000,3.500000,5.400000,16.042760,...,1.003200,0.008500,0.050718,0.001724,0.001362,0.072656,0.012617,0.024769,-4.221304,-11.108510
25%,353.000000,428.000000,1.180000,0.058400,4.134878,1287.000000,2101.500000,51.175000,54.900000,308.366905,...,3.167500,2.153050,0.290170,0.144239,0.141916,0.354313,0.176580,0.174873,-1.065734,-7.681506
50%,397.000000,487.000000,3.000000,0.265000,4.466868,3187.400000,2898.000000,64.200000,71.100000,418.478740,...,3.569600,2.506500,0.387053,0.191061,0.191400,0.458424,0.230597,0.223510,-0.638379,-7.242314
75%,479.000000,559.000000,6.020000,0.590000,4.731589,4189.000000,3492.200000,80.100000,89.675000,561.636140,...,3.992300,2.826350,0.516540,0.257266,0.255313,0.590859,0.302217,0.285918,-0.182861,-6.854552
max,1055.018450,1050.000000,2730.000000,1.000000,6.763428,7038.000000,14353.000000,194.800000,253.500000,2052.507780,...,6.310100,4.442200,0.999965,0.871599,0.834710,0.999866,0.955836,0.758038,2.306438,-4.428111

In [25]:
DyeDescription.to_csv('DyeDataLakeSummary.csv')

In [26]:
merged_df.to_csv('../../Data/Dyes/DyeDataUncurated.csv', index = False)